DECLARE @MyCounter int;

SET @MyCounter = 0;
SELECT @MyCounter;
SET @MyCounter =1;
SELECT @MyCounter;

DECLARE @document varchar(64);
SELECT @document='tetalhes do mysql'+' sem teste';

SELECT CHARINDEX('mysql', @document);
SELECT CHARINDEX('do', @document);
SELECT CHARINDEX('sem', @document);

SELECT DISTINCT('HAPPY' + ' HOUR S' + '2') AS RESULT;--concat

SELECT LTRIM('      TEM UM ESPACO DENTRO DA FRASE') --FROM sys.databases;

SELECT REPLACE('testando', 'ando', 'testando');

SELECT CEILING($666.66), CEILING($-666.66), CEILING($0);

SELECT FLOOR('2331');

SELECT STR(125.81441747, 10, 5);

DECLARE @DTA DATETIME;
SELECT @DTA = GETDATE();
SELECT @DTA;

DECLARE @DTAMAIS30 DATE;
SELECT @DTAMAIS30 = DATEADD(DAY, 30, GETDATE());
SELECT @DTAMAIS30;

DECLARE @TTT DATE;
SELECT @TTT = '01-01-2018';

DECLARE @DDA INT;
SELECT @DDA = DATEDIFF(DAY, @TTT, GETDATE());
SELECT @DDA;

DECLARE @DATE_PART_DIA INT;

SELECT @DATE_PART_DIA = DATEPART(YEAR, GETDATE());
SELECT @DATE_PART_DIA;
GO
DROP FUNCTION DBO.SOMA;
GO
CREATE FUNCTION SOMA(@a INT, @b INT) RETURNS INT
	AS
	BEGIN
		RETURN @a+@b
	END
GO

SELECT DBO.SOMA(1,10);